### ISSUE TITLE
Unable issue certificate over SSL/https

### ISSUE THREAD

**Issue by antonb55** [jimmypw/adcs#27]
Hi, i am trying to signing csr's  all paramaters are OK -password 'ourpass' -username 'ourusername' for -url we are trying https://  (certificate is self-signed by out CA) which we have on windows CA server we still become error message: 
"access is denied due to invalid credentials"

our password have generated special characters like "!"
credentials are correct over webbrowser it's possible to login with same cred.

Would appreciate any help here
Regards,
Anton

**Comment by jimmypw** [comment]
Hey, first sorry for the sluggish response - i've been busy.

What's not clear if you are running this command from a windows or linux cli. On linux if you're using special characters then they either need to be escaped

`-password Super\!SecurePa\$\$word`

Or single quoted

`-password 'Super!SecurePa$$word'`

TLS is unlikely the culprit here this has been well tested but do make sure that the certificate authority used to sign the certificate is in the trust stores of the OS.

One more thing to check (i'm digging long term memory here so this may be wildly inaccurate) is that some certificate template settings cause the template to require non-ntlm authentication. A good way to test this would be to assign the user permissions against the default 'Web Server Template' and try to generate a certificate using that. If this test was successful it would mean the escaping of the password was successful and something within the template is preventing the cli from authenticating.

Hope that helps. If you can share more details i may be able to provide a more specific answer.
